import { readFile, writeFile } from "node:fs/promises";

// Static sample requires only. Composition is imported directly from wave-music.
const manifest = JSON.parse(await readFile("assets/audio/sonora/manifest.json", "utf8"));
const entries = Object.entries(manifest.programs).map(
  ([name, samples]) =>
    `  ${JSON.stringify(name)}: [\n${samples.map((s) => `    { midi: ${s.midi}, asset: require('../../../assets/audio/sonora/${s.file}') },`).join("\n")}\n  ],`,
);
await writeFile(
  "src/lib/audio/sample-assets.ts",
  `// Generated by npm run sonora:build. Static requires let Metro bundle all samples offline.\nexport const sampleAssets: Record<string, { midi: number; asset: number }[]> = {\n${entries.join("\n")}\n};\n`,
);
