import { build } from "esbuild";
import { readFile, writeFile } from "node:fs/promises";

// Keep every class/helper inside one worklet closure. Class instances never cross
// runtimes and the original, portable Sonora sources remain directly editable.
const result = await build({
  entryPoints: ["src/lib/plant-live-engine.ts"],
  bundle: true,
  write: false,
  format: "iife",
  globalName: "Sonora",
  target: "es2015",
});
await writeFile(
  "src/lib/audio/sonora-runtime.ts",
  `// @ts-nocheck
// Generated by npm run sonora:build. Edit src/lib/sonora instead.
import type { LiveMusicEngine } from '../plant-live-engine';
import type { Configuration } from '../sonora/presets';
import type { Bank } from '../sonora/dsp';
export function createSonoraEngine(rate: number, elapsed: number, config: Configuration, bank: Bank): LiveMusicEngine {
  'worklet';
${result.outputFiles[0].text}
  return new Sonora.LiveMusicEngine(rate, elapsed, config, bank);
}
`,
);
const manifest = JSON.parse(await readFile("assets/audio/sonora/manifest.json", "utf8"));
const entries = Object.entries(manifest.programs).map(
  ([name, samples]) =>
    `  ${JSON.stringify(name)}: [\n${samples.map((s) => `    { midi: ${s.midi}, asset: require('../../../assets/audio/sonora/${s.file}') },`).join("\n")}\n  ],`,
);
await writeFile(
  "src/lib/audio/sample-assets.ts",
  `// Generated by npm run sonora:build. Static requires let Metro bundle all samples offline.\nexport const sampleAssets: Record<string, { midi: number; asset: number }[]> = {\n${entries.join("\n")}\n};\n`,
);
