// @ts-nocheck
// Generated by npm run sonora:build. Edit src/lib/sonora instead.
import type { LiveMusicEngine } from '../plant-live-engine';
import type { Configuration } from '../sonora/presets';
import type { Bank } from '../sonora/dsp';
export function createSonoraEngine(rate: number, elapsed: number, config: Configuration, bank: Bank): LiveMusicEngine {
  'worklet';
"use strict";
var Sonora = (() => {
  var __defProp = Object.defineProperty;
  var __defProps = Object.defineProperties;
  var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
  var __getOwnPropDescs = Object.getOwnPropertyDescriptors;
  var __getOwnPropNames = Object.getOwnPropertyNames;
  var __getOwnPropSymbols = Object.getOwnPropertySymbols;
  var __hasOwnProp = Object.prototype.hasOwnProperty;
  var __propIsEnum = Object.prototype.propertyIsEnumerable;
  var __pow = Math.pow;
  var __defNormalProp = (obj, key, value) => key in obj ? __defProp(obj, key, { enumerable: true, configurable: true, writable: true, value }) : obj[key] = value;
  var __spreadValues = (a, b) => {
    for (var prop in b || (b = {}))
      if (__hasOwnProp.call(b, prop))
        __defNormalProp(a, prop, b[prop]);
    if (__getOwnPropSymbols)
      for (var prop of __getOwnPropSymbols(b)) {
        if (__propIsEnum.call(b, prop))
          __defNormalProp(a, prop, b[prop]);
      }
    return a;
  };
  var __spreadProps = (a, b) => __defProps(a, __getOwnPropDescs(b));
  var __export = (target, all) => {
    for (var name in all)
      __defProp(target, name, { get: all[name], enumerable: true });
  };
  var __copyProps = (to, from, except, desc) => {
    if (from && typeof from === "object" || typeof from === "function") {
      for (let key of __getOwnPropNames(from))
        if (!__hasOwnProp.call(to, key) && key !== except)
          __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
    }
    return to;
  };
  var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);
  var __publicField = (obj, key, value) => __defNormalProp(obj, typeof key !== "symbol" ? key + "" : key, value);

  // src/lib/plant-live-engine.ts
  var plant_live_engine_exports = {};
  __export(plant_live_engine_exports, {
    LIVE_DELAY: () => LIVE_DELAY,
    LiveMusicEngine: () => LiveMusicEngine
  });

  // src/lib/sonora/signal.ts
  var clamp = (x, lo = 0, hi = 1) => Math.max(lo, Math.min(hi, x));
  var mean = (a) => a.reduce((s, x) => s + x / Math.max(1, a.length), 0);
  function median(a) {
    const s = [...a].sort((x, y) => x - y);
    return s.length ? s[Math.floor((s.length - 1) / 2)] / 2 + s[Math.floor(s.length / 2)] / 2 : 0;
  }
  var signedLog = (x) => Math.sign(x) * Math.log2(1 + Math.abs(x));
  var BIN_MS = 250;
  var GAP_SECONDS = 1.5;
  function describe(values, time, seq, cadence) {
    const log = values.map(signedLog), center = median(log);
    const residual = log.map((x) => Math.tanh((x - center) * 2) / 2);
    const spectrum = Array.from(
      { length: 9 },
      (_, k) => Math.abs(
        mean(
          residual.map(
            (x, j) => x * Math.cos(Math.PI * (j + 0.5) * (k + 1) / log.length)
          )
        )
      )
    );
    return {
      time,
      seq,
      level: mean(values),
      center,
      spread: Math.sqrt(mean(residual.map((x) => x * x))),
      roughness: mean(residual.slice(1).map((x, i) => Math.abs(x - residual[i]))),
      slope: mean(
        residual.map(
          (x, i) => x * (2 * i / Math.max(1, values.length - 1) - 1)
        )
      ),
      spectrum,
      profile: Array.from(
        { length: 10 },
        (_, j) => residual[Math.min(log.length - 1, Math.floor(j * log.length / 10))]
      ),
      cadence
    };
  }
  function createSignalAccumulator(onFrame) {
    let bucket = [], bin = -1, invalid = 0, suspect = 0, lastTime = -Infinity, lastSeq = -1;
    const flush = () => {
      if (!bucket.length) return;
      const first = bucket[0];
      onFrame(__spreadProps(__spreadValues({}, first), {
        time: bucket.at(-1).time,
        seq: bucket.at(-1).seq,
        level: mean(bucket.map((f) => f.level)),
        center: median(bucket.map((f) => f.center)),
        spread: mean(bucket.map((f) => f.spread)),
        roughness: mean(bucket.map((f) => f.roughness)),
        slope: mean(bucket.map((f) => f.slope)),
        cadence: mean(bucket.map((f) => f.cadence)),
        spectrum: first.spectrum.map(
          (_, j) => mean(bucket.map((f) => f.spectrum[j]))
        ),
        profile: first.profile.map(
          (_, j) => mean(bucket.map((f) => f.profile[j]))
        )
      }));
      bucket = [];
    };
    const push = (p) => {
      if (!Number.isSafeInteger(p.seq) || p.seq <= lastSeq || !Number.isFinite(p.elapsed_ms) || p.elapsed_ms < 0 || p.elapsed_ms < lastTime || p.error || !p.values || p.values.length !== 10 || !p.values.every(Number.isFinite)) {
        invalid++;
        return;
      }
      const nextBin = Math.floor(p.elapsed_ms / BIN_MS);
      if (nextBin !== bin) {
        flush();
        bin = nextBin;
      }
      const center = median(p.values);
      suspect += p.values.filter(
        (v) => Math.abs(v - center) > Math.max(100, Math.abs(center) * 100)
      ).length;
      const cadence = Number.isFinite(lastTime) ? (p.elapsed_ms - lastTime) / 1e3 : 0;
      bucket.push(describe(p.values, p.elapsed_ms / 1e3, p.seq, cadence));
      lastTime = p.elapsed_ms;
      lastSeq = p.seq;
    };
    return {
      push,
      flush,
      advance(elapsedMs) {
        if (bucket.length && elapsedMs >= (bin + 1) * BIN_MS) flush();
      },
      get invalid() {
        return invalid;
      },
      get suspect() {
        return suspect;
      },
      get pendingFrames() {
        return bucket.length;
      }
    };
  }

  // src/lib/sonora/synth-voices.ts
  var designs = {
    healing: [
      "silk",
      [0.8, 0.5, 0.24, 0.12, 0.07, 0.04, 0.02, 0.01],
      0.56,
      0.58,
      0,
      [7, 9, 12],
      2.8,
      3.8,
      0.36,
      3,
      0.18,
      0.12,
      0
    ],
    enlightenment: [
      "glass",
      [0.4, 0.9, 0.12, 0.48, 0.05, 0.18, 0.02, 0.08],
      0.64,
      0.54,
      2,
      [12, 7, 16],
      2.2,
      2.8,
      0.48,
      1.2,
      0.06,
      0.23,
      0.5
    ],
    chakra: [
      "choir",
      [0.4, 0.18, 0.78, 0.3, 0.6, 0.42, 0.15, 0.06],
      0.5,
      0.62,
      3,
      [7, 4, 12],
      3.3,
      4.5,
      0.6,
      2.2,
      0.12,
      0.14,
      0
    ],
    beauty: [
      "strings",
      [0.65, 0.48, 0.36, 0.28, 0.18, 0.14, 0.09, 0.06],
      0.62,
      0.5,
      1,
      [9, 12, 7],
      2.8,
      4,
      0.4,
      6,
      0.25,
      0.18,
      0
    ],
    astral: [
      "glass",
      [0.28, 0.64, 0.15, 0.82, 0.1, 0.32, 0.04, 0.13],
      0.7,
      0.5,
      4,
      [12, 19, 7],
      3,
      3.6,
      0.66,
      1.8,
      0.04,
      0.11,
      0.25
    ],
    connection: [
      "reed",
      [0.7, 0.02, 0.62, 0.03, 0.3, 0.01, 0.14, 0.02],
      0.44,
      0.58,
      2,
      [7, 12, 3],
      3.4,
      4.2,
      0.42,
      1.5,
      0.08,
      0.09,
      0
    ],
    illusion: [
      "choir",
      [0.22, 0.45, 0.22, 0.76, 0.34, 0.66, 0.26, 0.14],
      0.6,
      0.64,
      4,
      [9, 7, 12],
      3,
      4.1,
      0.7,
      4.5,
      0.2,
      0.26,
      0
    ],
    "space-time": [
      "silk",
      [0.46, 0.66, 0.12, 0.28, 0.08, 0.16, 0.02, 0.04],
      0.5,
      0.66,
      3,
      [12, 7, 9],
      3.8,
      4.8,
      0.82,
      5,
      0.2,
      0.07,
      0
    ],
    meditation: [
      "silk",
      [0.9, 0.15, 0.36, 0.06, 0.13, 0.025, 0.035, 0.01],
      0.5,
      0.48,
      0,
      [7, 12, 3],
      3.6,
      4.5,
      0.56,
      2,
      0.14,
      0.08,
      0
    ],
    energy: [
      "plume",
      [0.5, 0.62, 0.42, 0.28, 0.2, 0.12, 0.08, 0.04],
      0.66,
      0.6,
      1,
      [7, 12, 9],
      1.65,
      2.5,
      0.25,
      4,
      0.14,
      0.34,
      0.6
    ],
    mistery: [
      "reed",
      [0.36, 0.04, 0.82, 0.06, 0.44, 0.02, 0.21, 0.01],
      0.52,
      0.6,
      4,
      [7, 3, 12],
      3.3,
      3.9,
      0.62,
      2,
      0.07,
      0.16,
      0
    ],
    flower: [
      "choir",
      [0.32, 0.65, 0.48, 0.2, 0.73, 0.18, 0.13, 0.07],
      0.62,
      0.54,
      1,
      [9, 7, 12],
      2.65,
      3.6,
      0.38,
      3.5,
      0.13,
      0.29,
      0
    ],
    seed: [
      "plume",
      [0.75, 0.35, 0.56, 0.18, 0.21, 0.07, 0.1, 0.03],
      0.54,
      0.66,
      2,
      [7, 4, 12],
      2.1,
      2.6,
      0.29,
      1,
      0.05,
      0.21,
      0.9
    ],
    crystal: [
      "glass",
      [0.22, 0.86, 0.06, 0.7, 0.025, 0.4, 0.01, 0.18],
      0.74,
      0.46,
      3,
      [12, 7, 19],
      2.5,
      3,
      0.58,
      0.7,
      0.02,
      0.18,
      0.7
    ],
    mandala: [
      "choir",
      [0.34, 0.12, 0.62, 0.74, 0.24, 0.52, 0.17, 0.12],
      0.58,
      0.6,
      2,
      [7, 12, 3],
      3.5,
      4.5,
      0.72,
      5.5,
      0.18,
      0.13,
      0
    ],
    peace: [
      "silk",
      [0.6, 0.52, 0.11, 0.19, 0.045, 0.055, 0.02, 0.01],
      0.6,
      0.44,
      0,
      [7, 12, 4],
      3.8,
      4.8,
      0.66,
      1.6,
      0.1,
      0.06,
      0
    ],
    sun: [
      "strings",
      [0.44, 0.72, 0.36, 0.4, 0.22, 0.18, 0.13, 0.08],
      0.68,
      0.5,
      3,
      [12, 9, 7],
      2.6,
      3.8,
      0.34,
      4.2,
      0.22,
      0.2,
      0
    ],
    lead: [
      "reed",
      [0.84, 0.11, 0.52, 0.08, 0.32, 0.05, 0.18, 0.03],
      0.6,
      0.62,
      1,
      [7, 3, 12],
      1.85,
      2.7,
      0.28,
      2.8,
      0.12,
      0.3,
      0.15
    ],
    infinity: [
      "strings",
      [0.54, 0.28, 0.64, 0.32, 0.34, 0.2, 0.18, 0.09],
      0.64,
      0.58,
      4,
      [12, 7, 9],
      3.2,
      4.4,
      0.76,
      7,
      0.24,
      0.1,
      0
    ],
    "non-duality": [
      "plume",
      [0.42, 0.74, 0.16, 0.52, 0.14, 0.3, 0.06, 0.12],
      0.65,
      0.62,
      0,
      [7, 12, 4],
      2.4,
      3.2,
      0.44,
      3,
      0.1,
      0.25,
      0.4
    ]
  };
  var SYNTH_VOICES = Object.fromEntries(
    Object.entries(designs).map(
      ([
        id,
        [
          family,
          harmonics,
          register,
          range,
          trace,
          intervals,
          pace,
          sustain,
          response,
          detune,
          blend,
          evolution,
          decay
        ]
      ]) => [
        id,
        {
          family,
          harmonics,
          register,
          range,
          trace,
          intervals,
          pace,
          sustain,
          response,
          detune,
          blend,
          evolution,
          decay
        }
      ]
    )
  );
  var synthVoice = (id) => {
    var _a;
    return (_a = SYNTH_VOICES[id]) != null ? _a : SYNTH_VOICES.healing;
  };

  // src/lib/sonora/gesture.ts
  function createGestureDetector() {
    let previous = null, began = 0, lastGreeting = -Infinity;
    let history = [];
    let candidate = null;
    let active = null;
    return {
      get engaged() {
        return candidate !== null || active !== null;
      },
      push(frame) {
        const gap = previous !== null && frame.time - previous.time > GAP_SECONDS;
        if (!previous || gap) {
          previous = frame;
          began = frame.time;
          history = [];
          candidate = null;
          active = null;
        }
        const step = Math.abs(frame.center - previous.center);
        previous = frame;
        history = history.filter((p) => frame.time - p.time <= 6);
        if (active) {
          const returned = Math.abs(frame.center - active.baseline) < Math.max(0.06, active.contrast * 0.18);
          active.settled = returned ? active.settled + 1 : 0;
          if (active.settled >= 2 || frame.time - active.time > 8) {
            active = null;
            candidate = null;
            history = [];
          }
          return null;
        }
        const baseline = history.length ? median(history.map((p) => p.center)) : frame.center;
        const noise = median(history.map((p) => p.step));
        const threshold = Math.max(0.18, noise * 12);
        const deviation = Math.abs(frame.center - baseline);
        if (candidate) {
          const contrast = Math.abs(candidate.center - candidate.baseline);
          const sameDirection = Math.sign(frame.center - candidate.baseline) === Math.sign(candidate.center - candidate.baseline);
          if (frame.time - candidate.time <= GAP_SECONDS && sameDirection && Math.abs(frame.center - candidate.center) < contrast * 0.45) {
            active = {
              baseline: candidate.baseline,
              contrast,
              time: frame.time,
              settled: 0
            };
            candidate = null;
            lastGreeting = frame.time;
            return { contrast, source: frame.seq, time: frame.time };
          }
          candidate = null;
        }
        if (frame.time - began >= 2 && frame.time - lastGreeting >= 3 && step > threshold && deviation > threshold) {
          candidate = { baseline, center: frame.center, time: frame.time };
          return null;
        }
        history.push({ time: frame.time, center: frame.center, step });
        return null;
      }
    };
  }

  // src/lib/sonora/presets.ts
  var SCALES = {
    Chromatic: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11],
    Ionian: [0, 2, 4, 5, 7, 9, 11],
    Doric: [0, 2, 3, 5, 7, 9, 10],
    Phrygian: [0, 1, 3, 5, 7, 8, 10],
    Lydian: [0, 2, 4, 6, 7, 9, 11],
    Mixolydian: [0, 2, 4, 5, 7, 9, 10],
    Aeolian: [0, 2, 3, 5, 7, 8, 10],
    Locrio: [0, 1, 3, 5, 6, 8, 10],
    "Major third": [0, 4, 8],
    "Minor third": [0, 3, 6, 9],
    Fifth: [0, 7],
    "Major Blues": [0, 2, 3, 4, 7, 9],
    "Minor Blues": [0, 3, 5, 6, 7, 10],
    Diminish: [0, 2, 3, 5, 6, 8, 9, 11],
    "Maj Pentatonic": [0, 2, 4, 7, 9],
    "Min Pentatonic": [0, 3, 5, 7, 10],
    Spanish: [0, 1, 4, 5, 7, 8, 10],
    Gypsy: [0, 2, 3, 6, 7, 8, 11],
    Arabian: [0, 2, 4, 5, 6, 8, 10],
    Indian: [0, 1, 4, 5, 7, 8, 11],
    Ryukyu: [0, 4, 5, 7, 11],
    wholetone: [0, 2, 4, 6, 8, 10]
  };
  var synths = [
    ["Healing", "Ionian", "2-6", "30/99", "57/86", "-", "50/99"],
    ["Enlightenment", "Maj Pentatonic", "3-5", "25/99", "84/75", "-", "0/99"],
    ["Chakra", "Ionian", "2-5", "84/81", "95/92", "-", "50/15"],
    ["Beauty", "Lydian", "3-6", "95/69", "73/99", "95/86", "100/15"],
    ["Astral", "Lydian", "3-6", "52/63", "41/63", "52/63", "100/15"],
    ["Connection", "Min Pentatonic", "2-4", "19/99", "100/99", "100/99", "0/99"],
    ["Illusion", "Ionian", "3-5", "84/86", "100/99", "84/98", "82/99"],
    ["Space Time", "Doric", "2-5", "79/81", "52/86", "-", "100/9"],
    ["Meditation", "0,3,7", "2-5", "73/92", "30/99", "-", "39/99"],
    ["Energy", "Lydian", "3-5", "95/92", "73/52", "100/98", "60/38"],
    ["Mistery", "Ionian", "2-5", "73/63", "41/75", "-", "100/26"],
    ["Flower", "Locrio", "3-5", "8/99", "24/99", "73/86", "100/61"],
    ["Seed", "Maj Pentatonic", "3-5", "68/75", "-", "95/75", "39/61"],
    ["Crystal", "Gypsy", "4-6", "63/58", "73/86", "-", "100/21"],
    ["Mandala", "Min Pentatonic", "2-5", "41/99", "100/98", "100/99", "100/3"],
    ["Peace", "2,3,5,6", "3-5", "100/92", "41/75", "95/86", "50/0"],
    ["Sun", "Doric", "3-6", "95/86", "100/99", "73/86", "100/21"],
    ["Lead", "Min Pentatonic", "3-5", "73/75", "100/99", "73/11", "50/73"],
    ["Infinity", "Maj Pentatonic", "3-6", "14/99", "52/86", "95/52", "100/26"],
    ["Non Duality", "Ryukyu", "3-5", "90/34", "19/99", "73/63", "100/9"]
  ];
  var instruments = [
    [
      "Pan Flute",
      "Maj Pentatonic",
      "2-4",
      "14/86",
      "-",
      "-",
      "50/26",
      "pan_flute"
    ],
    [
      "Hang Drum",
      "0,2,3,6,7,10",
      "1-6",
      "14/99",
      "-",
      "-",
      "100/0",
      "steel_drums"
    ],
    ["Koshi", "Ryukyu", "1-3", "35/93", "19/75", "79/81", "100/0", "model:chime"],
    [
      "Church Organ",
      "Mixolydian",
      "1-4",
      "8/99",
      "84/75",
      "-",
      "50/26",
      "church_organ"
    ],
    [
      "Pianoforte",
      "Lydian",
      "2-5",
      "19/99",
      "52/75",
      "-",
      "100/0",
      "acoustic_grand_piano"
    ],
    ["Woodwinds", "Locrio", "1-4", "8/99", "-", "-", "100/0", "oboe"],
    ["Marimba", "Lydian", "1-4", "3/99", "41/52", "-", "100/0", "marimba"],
    ["Tibetan Bell", "Locrio", "1-3", "3/99", "-", "-", "100/0", "model:bowl"],
    ["Xilophone", "Ryukyu", "1-4", "25/40", "84/86", "-", "100/0", "xylophone"],
    ["Sitar", "0,1,4,7,10", "2-6", "30/99", "100/99", "73/40", "0/99", "sitar"],
    [
      "Mixed Choir",
      "Locrio",
      "2-6",
      "8/99",
      "19/17",
      "-",
      "100/73",
      "choir_aahs"
    ],
    [
      "Metal Bell",
      "Ionian",
      "1-5",
      "14/99",
      "41/75",
      "-",
      "100/0",
      "tubular_bells"
    ],
    [
      "Choir and Organ",
      "Lydian",
      "1-4",
      "8/99",
      "30/52",
      "-",
      "100/73",
      "choir_organ"
    ],
    [
      "Brass Ensemble",
      "Aeolian",
      "1-5",
      "3/99",
      "25/40",
      "-",
      "100/38",
      "brass_section"
    ],
    [
      "Orchestal Strings",
      "Aeolian",
      "1-4",
      "3/99",
      "25/40",
      "-",
      "100/73",
      "string_ensemble_1"
    ],
    [
      "Guitar",
      "Min Pentatonic",
      "2-5",
      "41/29",
      "25/34",
      "30/17",
      "100/0",
      "acoustic_guitar_nylon"
    ],
    [
      "Harp",
      "Lydian",
      "2-6",
      "19/99",
      "41/86",
      "84/29",
      "100/0",
      "orchestral_harp"
    ]
  ];
  var pair = (s) => s === "-" ? [0, 0] : s.split("/").map(Number);
  function make(row, kind, flavor) {
    var _a;
    const [name, scale, oct, del, rev, cho, env, source] = row, id = name.toLowerCase().replaceAll(" ", "-");
    const [dw, dr] = pair(del), [rw, ra] = pair(rev), [cd, cr] = pair(cho), [er, ea] = pair(env);
    return {
      id,
      name,
      kind,
      flavor,
      program: (source == null ? void 0 : source.startsWith("model:")) ? void 0 : source,
      model: (source == null ? void 0 : source.startsWith("model:")) ? source.slice(6) : void 0,
      patch: {
        preset: id,
        scale: SCALES[scale] ? scale : "Custom",
        notes: [...(_a = SCALES[scale]) != null ? _a : scale.split(",").map(Number)],
        octaves: oct.split("-").map(Number),
        tuning: 440,
        velocity: { range: 127, center: 72 },
        delay: { on: del !== "-", wet: dw, rate: dr },
        reverb: { on: rev !== "-", wet: rw, amount: ra },
        chorus: { on: cho !== "-", depth: cd, rate: cr },
        envelope: { on: env !== "-", release: er, attack: ea }
      }
    };
  }
  var SYNTHS = synths.map((r, i) => make(r, "synth", i));
  var INSTRUMENTS = instruments.map((r, i) => make(r, "instrument", i));
  var PRESETS = [...SYNTHS, ...INSTRUMENTS];
  var preset = (id) => {
    var _a;
    return (_a = PRESETS.find((p) => p.id === id)) != null ? _a : SYNTHS[0];
  };
  var copyPatch = (id) => JSON.parse(JSON.stringify(preset(id).patch));
  function defaultConfiguration() {
    return {
      version: 1,
      synth: copyPatch("healing"),
      instrument: copyPatch("harp"),
      speed: 1,
      synthLevel: 0.55,
      instrumentLevel: 0.95,
      greetingLevel: 1
    };
  }
  var limit = (n, a, b) => Number.isFinite(n) ? Math.max(a, Math.min(b, n)) : a;
  function sanitizeConfiguration(input) {
    const c = JSON.parse(JSON.stringify(input));
    for (const lane of ["synth", "instrument"]) {
      const p = c[lane];
      if (!PRESETS.some((x) => x.id === p.preset && x.kind === lane))
        throw Error("Preset no v\xE1lido");
      p.notes = [
        ...new Set(
          p.notes.filter((n) => Number.isInteger(n) && n >= 0 && n < 12)
        )
      ].sort((a, b) => a - b);
      if (!p.notes.length) throw Error("Selecciona al menos una nota");
      p.octaves = [
        Math.round(limit(p.octaves[0], 1, 6)),
        Math.round(limit(p.octaves[1], 1, 6))
      ].sort((a, b) => a - b);
      p.tuning = limit(p.tuning, 392, 494);
      for (const effect of [p.delay, p.reverb, p.chorus, p.envelope])
        for (const key of Object.keys(effect))
          if (key !== "on")
            effect[key] = limit(
              effect[key],
              0,
              100
            );
      p.velocity = {
        range: limit(p.velocity.range, 0, 127),
        center: limit(p.velocity.center, 0, 127)
      };
    }
    c.speed = limit(c.speed, 0.25, 2);
    c.synthLevel = limit(c.synthLevel, 0, 1);
    c.instrumentLevel = limit(c.instrumentLevel, 0, 1);
    c.greetingLevel = limit(c.greetingLevel, 0.2, 1);
    c.version = 1;
    return c;
  }
  function notePool(p) {
    const notes = [];
    for (let o = p.octaves[0]; o <= p.octaves[1]; o++)
      for (const n of p.notes) notes.push(12 * (o + 1) + n);
    return notes;
  }

  // src/lib/sonora/composer.ts
  var fraction = (n) => n - Math.floor(n);
  var Composer = class {
    constructor(config = defaultConfiguration()) {
      __publicField(this, "config");
      __publicField(this, "gesture", createGestureDetector());
      __publicField(this, "events", []);
      __publicField(this, "previous", null);
      __publicField(this, "serial", 0);
      __publicField(this, "lastLead", -Infinity);
      __publicField(this, "lastSynth", -Infinity);
      __publicField(this, "baseline", 0);
      __publicField(this, "lastPitch", -1);
      __publicField(this, "stopped", false);
      __publicField(this, "movement", 0);
      __publicField(this, "phrase", 0);
      this.config = sanitizeConfiguration(config);
    }
    configure(config, time) {
      this.config = sanitizeConfiguration(config);
      this.events.push(
        { type: "release", time, lane: "synth" },
        { type: "release", time, lane: "instrument" }
      );
      this.lastLead = this.lastSynth = -Infinity;
    }
    emit(f, lane, midi, duration, velocity, pan, delay = 0) {
      const patch = lane === "greeting" ? __spreadProps(__spreadValues({}, copyPatch("harp")), {
        notes: [...this.config.instrument.notes],
        tuning: this.config.instrument.tuning
      }) : this.config[lane];
      const note = {
        id: this.serial++,
        time: f.time + delay,
        sourceTime: f.time,
        source: f.seq,
        midi,
        velocity: clamp(velocity, 0, 127),
        duration,
        lane,
        patch,
        color: clamp(Math.log1p(f.roughness * 140) / 3),
        pan
      };
      this.events.push({ type: "note", time: note.time, note });
      return note;
    }
    push(f) {
      if (this.stopped || this.previous && f.time <= this.previous.time) return;
      const first = !this.previous, delta = first ? 0 : f.center - this.previous.center;
      const gap = this.previous && f.time - this.previous.time > 1.5;
      if (first || gap) {
        this.baseline = f.center;
        this.movement = 0;
        this.phrase = 0;
        this.lastLead = this.lastSynth = -Infinity;
      }
      const gesture = this.gesture.push(f);
      const motion = 1 - Math.exp(-Math.abs(delta) * 24 - f.roughness * 8), detail = 1 - Math.exp(-f.spread * 18);
      const profileScale = Math.max(4e-3, f.spread);
      const profileChange = first ? 0 : f.profile.reduce(
        (sum, x, i) => sum + Math.abs(x - this.previous.profile[i]),
        0
      ) / (10 * profileScale);
      this.movement += Math.abs(delta) * 12 + Math.min(1, profileChange) * 0.32;
      const bandSum = Math.max(
        1e-4,
        f.spectrum.reduce((sum, x) => sum + x, 0)
      );
      const bands = f.spectrum.map((x) => Math.sqrt(x / bandSum));
      this.events.push({
        type: "expression",
        time: f.time,
        expression: {
          brightness: detail * 0.5 + motion * 0.3 + bands.slice(4).reduce((a, b) => a + b, 0) * 0.08,
          energy: motion * 0.55 + detail * 0.45,
          direction: Math.tanh(f.slope / profileScale),
          bands
        }
      });
      this.baseline += (f.center - this.baseline) * 0.08;
      const shape = f.spectrum.reduce((s, x, i) => s + x * (i + 1), 0) / Math.max(
        1e-8,
        f.spectrum.reduce((s, x) => s + x, 0)
      ) / 9;
      const position = fraction(f.center * 0.38196601125 + shape * 0.43);
      const contour = Math.tanh((f.center - this.baseline) * 60 + f.slope * 35);
      const leadPool = notePool(this.config.instrument);
      const profileAt = Math.floor(this.phrase % f.profile.length);
      const detailStep = Math.tanh(
        (f.profile[profileAt] - f.profile[(profileAt + 4) % 10]) / profileScale
      ) * 2.4;
      const index = Math.round(
        (0.28 + position * 0.64) * (leadPool.length - 1) + contour * 2 + detailStep
      );
      const lead = leadPool[Math.round(clamp(index, 0, leadPool.length - 1))];
      const velocity = (p) => clamp(
        p.velocity.center + p.velocity.range * 0.35 * Math.tanh(motion + detail + contour * 0.6 - 0.35),
        0,
        127
      );
      const leadPeriod = (1.05 + (1 - detail) * 0.75 + (1 - motion) * 0.35 + (1 - Math.min(1, profileChange)) * 0.25) / this.config.speed;
      if (f.time - this.lastLead >= leadPeriod || Math.abs(lead - this.lastPitch) >= 5 && f.time - this.lastLead > 0.35 / this.config.speed) {
        this.emit(
          f,
          "instrument",
          lead,
          (1.1 + detail * 0.9) / this.config.speed,
          velocity(this.config.instrument),
          -0.12 + f.slope * 0.4
        );
        if (this.movement > 0.65 && !gesture && !this.gesture.engaged) {
          const responseStep = Math.round(
            Math.tanh(f.profile[(profileAt + 6) % 10] / profileScale) * 3
          );
          const reply = leadPool[Math.round(clamp(index + responseStep, 0, leadPool.length - 1))];
          if (reply !== lead)
            this.emit(
              f,
              "instrument",
              reply,
              (0.7 + detail * 0.8) / this.config.speed,
              velocity(this.config.instrument) * 0.68,
              0.2 + Math.tanh(f.slope / profileScale) * 0.2,
              (0.32 + (1 - motion) * 0.3) / this.config.speed
            );
          this.phrase += 1 + Math.min(2, Math.floor(this.movement));
          this.movement %= 0.65;
        }
        this.lastLead = f.time;
        this.lastPitch = lead;
      }
      const voice = synthVoice(this.config.synth.preset);
      const synthPeriod = voice.pace * (1.05 + (1 - detail) * 0.25 + (1 - motion) * 0.15) / this.config.speed;
      if (f.time - this.lastSynth >= synthPeriod) {
        const pool = notePool(this.config.synth);
        const trace = Math.tanh(
          f.profile.reduce(
            (sum, x, i) => sum + x * Math.sin((i + 1) * (voice.trace + 1) * Math.PI / 11),
            0
          ) / (profileScale * 3)
        );
        const register = clamp(
          voice.register + (position - 0.5) * voice.range + trace * 0.15 + contour * 0.08,
          0.05,
          0.95
        );
        const target = pool[0] + register * (pool[pool.length - 1] - pool[0]);
        const nearest = (target2, candidates) => candidates.reduce(
          (best, n) => Math.abs(n - target2) < Math.abs(best - target2) ? n : best,
          candidates[0]
        );
        const root = nearest(target, pool);
        const dominant = bands.reduce(
          (best, x, i) => x > bands[best] ? i : best,
          0
        );
        const interval = voice.intervals[dominant % voice.intervals.length];
        const companionTarget = root + interval <= pool[pool.length - 1] ? root + interval : root - interval;
        const others = pool.filter((n) => n !== root);
        const companion = others.length ? nearest(companionTarget, others) : root;
        this.emit(
          f,
          "synth",
          root,
          voice.sustain * (0.85 + detail * 0.3) / this.config.speed,
          velocity(this.config.synth) * 0.8,
          -0.32
        );
        if (companion !== root)
          this.emit(
            f,
            "synth",
            companion,
            voice.sustain * (0.95 + motion * 0.2) / this.config.speed,
            velocity(this.config.synth) * 0.64,
            0.32,
            (voice.response + (1 - motion) * 0.18) / this.config.speed
          );
        this.lastSynth = f.time;
      }
      if (gesture) this.greet(f, lead);
      this.previous = f;
    }
    greet(f, lead) {
      const pool = notePool(__spreadProps(__spreadValues({}, this.config.instrument), {
        octaves: [4, 5]
      })).filter((n) => n <= 79);
      const closest = pool.reduce(
        (best, n, i) => Math.abs(n - (lead + 7)) < Math.abs(pool[best] - (lead + 7)) ? i : best,
        0
      );
      const at = Math.max(0, Math.min(pool.length - 3, closest));
      this.emit(f, "greeting", pool[at], 3.4, 100, -0.3);
      this.emit(
        f,
        "greeting",
        pool[Math.min(pool.length - 1, at + 2)],
        3,
        82,
        0.3,
        0.68
      );
    }
    advance(time) {
      if (this.previous && time - this.previous.time > 1.5) {
        this.events.push({ type: "release", time });
        this.previous = null;
      }
    }
    finish(time) {
      this.stopped = true;
      this.events.push({ type: "release", time });
    }
    audition(lane, time) {
      const f = {
        time,
        seq: -1,
        center: 14,
        level: 2e4,
        spread: 0.02,
        roughness: 0.01,
        slope: 0,
        spectrum: Array(9).fill(0.01),
        profile: Array(10).fill(0),
        cadence: 0
      };
      const patch = lane === "synth" ? this.config.synth : this.config.instrument, pool = notePool(
        lane === "greeting" ? __spreadProps(__spreadValues({}, patch), { octaves: [4, 5] }) : patch
      ), at = Math.floor(pool.length * 0.55);
      if (lane === "greeting") {
        this.greet(f, pool[at] - 7);
        return;
      }
      for (let j = 0; j < 3; j++)
        this.emit(
          f,
          lane,
          pool[Math.min(pool.length - 1, at + j * 2)],
          2.8,
          95,
          (j - 1) * 0.2,
          j * 0.45
        );
    }
    drain() {
      const result = this.events;
      this.events = [];
      return result;
    }
    get latest() {
      return this.previous;
    }
  };
  var noteName = (midi) => ["C", "C#", "D", "D#", "E", "F", "F#", "G", "G#", "A", "A#", "B"][(Math.round(midi) % 12 + 12) % 12] + (Math.floor(midi / 12) - 1);

  // src/lib/sonora/dsp.ts
  var RELEASE_SECONDS = 6;
  var TAU = Math.PI * 2;
  var SIZE = 2048;
  var sine = Float32Array.from(
    { length: SIZE + 1 },
    (_, i) => Math.sin(i * TAU / SIZE)
  );
  var sin = (phase) => {
    const x = (phase - Math.floor(phase)) * SIZE, i = x | 0;
    return sine[i] + (sine[i + 1] - sine[i]) * (x - i);
  };
  var smooth = (x) => {
    const v = clamp(x);
    return v * v * (3 - 2 * v);
  };
  var Effects = class {
    constructor(rate) {
      __publicField(this, "dl");
      __publicField(this, "dr");
      __publicField(this, "at", 0);
      __publicField(this, "chorusPhase", 0);
      __publicField(this, "lines");
      __publicField(this, "indices", new Int32Array(4));
      __publicField(this, "damp", new Float64Array(4));
      __publicField(this, "rate");
      __publicField(this, "output", [0, 0]);
      this.rate = rate;
      this.dl = new Float32Array(Math.ceil(rate * 1.3));
      this.dr = new Float32Array(this.dl.length);
      this.lines = [0.097, 0.131, 0.173, 0.211].map(
        (x) => new Float32Array(Math.ceil(rate * x))
      );
    }
    tap(b, seconds) {
      const x = (this.at - seconds * this.rate + b.length) % b.length, i = x | 0;
      return b[i] + (b[(i + 1) % b.length] - b[i]) * (x - i);
    }
    process(l, r, p) {
      const d = p.delay, c = p.chorus, rv = p.reverb;
      const dt = 0.07 + 1.1 * (1 - d.rate / 100), echoL = this.tap(this.dr, dt), echoR = this.tap(this.dl, dt * 1.017);
      this.dl[this.at] = l + (d.on ? echoL * 0.32 : 0);
      this.dr[this.at] = r + (d.on ? echoR * 0.32 : 0);
      if (c.on) {
        this.chorusPhase += (0.08 + c.rate / 100 * 1.12) / this.rate;
        const depth = c.depth / 100;
        const cl = this.tap(
          this.dl,
          0.018 + sin(this.chorusPhase) * 3e-3 * depth
        ), cr = this.tap(
          this.dr,
          0.021 + sin(this.chorusPhase + 0.25) * 3e-3 * depth
        );
        l = l * (1 - depth * 0.35) + cl * depth * 0.35;
        r = r * (1 - depth * 0.35) + cr * depth * 0.35;
      }
      if (d.on) {
        const wet = d.wet / 100;
        l = l * (1 - wet) + echoL * wet;
        r = r * (1 - wet) + echoR * wet;
      }
      let sum = 0;
      for (let j = 0; j < 4; j++) {
        this.damp[j] += (this.lines[j][this.indices[j]] - this.damp[j]) * 0.3;
        sum += this.damp[j];
      }
      const feedback = 0.48 + rv.amount / 100 * 0.4;
      for (let j = 0; j < 4; j++) {
        this.lines[j][this.indices[j]] = (j % 2 ? r : l) * 0.3 + (sum * 0.5 - this.damp[j]) * feedback;
        this.indices[j] = (this.indices[j] + 1) % this.lines[j].length;
      }
      const earlyL = this.tap(this.dl, 0.023), earlyR = this.tap(this.dr, 0.031), wetL = earlyL * 0.78 + (this.damp[0] + this.damp[1] - this.damp[2] - this.damp[3]) * 0.22, wetR = earlyR * 0.78 + (this.damp[0] - this.damp[1] + this.damp[2] - this.damp[3]) * 0.22;
      this.at = (this.at + 1) % this.dl.length;
      if (rv.on) {
        const wet = rv.wet / 100;
        l = l * (1 - wet) + wetL * wet;
        r = r * (1 - wet) + wetR * wet;
      }
      this.output[0] = l;
      this.output[1] = r;
      return this.output;
    }
  };
  function prepareVoice(rate, bank, n) {
    const sampleFor = (program2, midi) => {
      var _a, _b;
      return (_b = (_a = program2 ? bank[program2] : void 0) == null ? void 0 : _a.reduce((a, b) => Math.abs(a.midi - midi) <= Math.abs(b.midi - midi) ? a : b)) != null ? _b : null;
    };
    if (n.velocity <= 0) return;
    const desc = preset(n.patch.preset), isGreeting = n.lane === "greeting";
    const program = isGreeting ? "orchestral_harp" : desc.program;
    const sample = sampleFor(
      program === "choir_organ" ? "choir_aahs" : program,
      n.midi
    ), sample2 = program === "choir_organ" ? sampleFor("church_organ", n.midi) : null;
    if (n.lane !== "synth" && !sample && !desc.model) return;
    const frequency = n.patch.tuning * __pow(2, (n.midi - 69) / 12), flavor = desc.flavor;
    const design = synthVoice(n.patch.preset);
    const harmonics = design.harmonics.map(
      (x, i) => frequency * (i + 1) < rate * 0.42 ? x : 0
    );
    const normalization = Math.min(
      1.6,
      0.96 / Math.sqrt(harmonics.reduce((sum, x) => sum + x * x, 0))
    );
    for (let i = 0; i < harmonics.length; i++) harmonics[i] *= normalization;
    return {
      note: n,
      sample,
      sample2,
      position: 0,
      position2: 0,
      increment: sample ? sample.rate / rate * __pow(2, (n.midi - sample.midi) / 12) * n.patch.tuning / 440 : 0,
      increment2: sample2 ? sample2.rate / rate * __pow(2, (n.midi - sample2.midi) / 12) * n.patch.tuning / 440 : 0,
      phase: 0,
      phase2: 0.07,
      detuneRatio: __pow(2, design.detune / 1200),
      design,
      frequency,
      attenuation: Math.min(1, Math.sqrt(880 / frequency)),
      harmonics,
      ratios: desc.model === "bowl" ? [1, 2.71, 4.05, 5.43] : [1, 2, 3, 4],
      attack: isGreeting ? 0.14 : n.patch.envelope.on ? 4e-3 + (n.lane === "synth" ? 1.3 : 0.45) * __pow(n.patch.envelope.attack / 100, 2) : n.lane === "synth" ? 0.08 : 4e-3,
      release: isGreeting ? 2.8 : n.patch.envelope.on ? 0.06 + 3.5 * __pow(n.patch.envelope.release / 100, 2) : 0.35,
      stop: n.time + n.duration,
      forced: Infinity,
      panL: Math.sqrt((1 - clamp(n.pan, -1, 1)) / 2),
      panR: Math.sqrt((1 + clamp(n.pan, -1, 1)) / 2),
      flavor,
      model: desc.model,
      gain: (isGreeting ? 0.34 : n.lane === "synth" ? 0.17 : 0.2) * __pow(n.velocity / 100, 1.15)
    };
  }
  var AudioCore = class {
    constructor(rate, config = defaultConfiguration(), bank = {}) {
      __publicField(this, "config");
      __publicField(this, "bank");
      __publicField(this, "voices", []);
      __publicField(this, "pending", []);
      __publicField(this, "cancelled", /* @__PURE__ */ new Set());
      __publicField(this, "cursor", 0);
      __publicField(this, "duck", 1);
      __publicField(this, "greetingAt", -Infinity);
      __publicField(this, "expression", {
        brightness: 0.35,
        energy: 0.3,
        direction: 0,
        bands: Array(9).fill(0.33)
      });
      __publicField(this, "targetExpression", this.expression);
      __publicField(this, "expressionBands", new Float64Array(9).fill(0.33));
      __publicField(this, "buses");
      __publicField(this, "dcL", 0);
      __publicField(this, "dcR", 0);
      __publicField(this, "meters", { synth: 0, instrument: 0, greeting: 0 });
      __publicField(this, "rate");
      this.rate = rate;
      this.config = config;
      this.bank = bank;
      this.buses = {
        synth: new Effects(rate),
        instrument: new Effects(rate),
        greeting: new Effects(rate)
      };
    }
    configure(config, bank = this.bank) {
      this.config = config;
      this.bank = bank;
    }
    schedule(events) {
      this.pending.push(...events);
      this.pending.sort((a, b) => a.time - b.time);
    }
    start(n) {
      const voice = prepareVoice(this.rate, this.bank, n);
      if (!voice) return;
      const same = this.voices.filter(
        (v) => v.note.lane === n.lane && v.forced === Infinity
      );
      const limit2 = n.lane === "synth" ? 6 : n.lane === "instrument" ? 8 : 4;
      if (same.length >= limit2) same[0].forced = this.time + 0.025;
      this.voices.push(voice);
      if (n.lane === "greeting") this.greetingAt = this.time;
    }
    render(l, r) {
      let at = 0, maxS = 0, maxI = 0, maxG = 0;
      const dc = 1 - Math.exp(-TAU * 18 / this.rate);
      const expressionSlew = 1 - Math.exp(-1 / (0.18 * this.rate));
      const duckAttack = 1 - Math.exp(-1 / (0.08 * this.rate));
      const duckRelease = 1 - Math.exp(-1 / (0.8 * this.rate));
      const lanes = ["synth", "instrument", "greeting"];
      const levels = [
        this.config.synthLevel,
        this.config.instrumentLevel,
        this.config.greetingLevel
      ];
      const greetPatch = __spreadProps(__spreadValues({}, this.config.instrument), {
        delay: { on: true, wet: 12, rate: 77 },
        reverb: { on: true, wet: 42, amount: 76 },
        chorus: { on: true, depth: 25, rate: 13 }
      });
      const patches = [this.config.synth, this.config.instrument, greetPatch];
      for (let i = 0; i < l.length; i++, this.cursor++) {
        const time = this.cursor / this.rate;
        while (at < this.pending.length && this.pending[at].time <= time) {
          const e = this.pending[at++];
          if (e.type === "note") {
            if (this.cancelled.has(e.note.id)) this.cancelled.delete(e.note.id);
            else this.start(e.note);
          } else if (e.type === "expression") {
            this.targetExpression = e.expression;
          } else {
            for (const v of this.voices)
              if (!e.lane || v.note.lane === e.lane)
                v.forced = Math.min(v.forced, time + 0.15);
            for (let j = at; j < this.pending.length; j++) {
              const q = this.pending[j];
              if (q.type === "note" && q.note.sourceTime <= e.time && (!e.lane || q.note.lane === e.lane))
                this.cancelled.add(q.note.id);
            }
          }
        }
        this.expression.brightness += (this.targetExpression.brightness - this.expression.brightness) * expressionSlew;
        this.expression.energy += (this.targetExpression.energy - this.expression.energy) * expressionSlew;
        this.expression.direction += (this.targetExpression.direction - this.expression.direction) * expressionSlew;
        for (let band = 0; band < 9; band++)
          this.expressionBands[band] += (this.targetExpression.bands[band] - this.expressionBands[band]) * expressionSlew;
        let sl = 0, sr = 0, il = 0, ir = 0, gl = 0, gr = 0;
        const brightness = clamp(this.expression.brightness), energy = clamp(this.expression.energy);
        for (const v of this.voices) {
          const age = time - v.note.time;
          if (time > Math.min(v.stop + v.release, v.forced)) continue;
          const envelope = (age < v.attack ? smooth(age / v.attack) : 1) * (time < v.stop ? 1 : 1 - smooth((time - v.stop) / v.release)) * (v.forced === Infinity ? 1 : clamp((v.forced - time) / 0.025));
          let value = 0;
          if (v.sample) {
            const p = Math.floor(v.position), a = v.sample.data;
            if (p < a.length - 1)
              value = a[p] + (a[p + 1] - a[p]) * (v.position - p);
            v.position += v.increment;
            if (v.sample2) {
              const q = Math.floor(v.position2), b = v.sample2.data;
              const other = q < b.length - 1 ? b[q] + (b[q + 1] - b[q]) * (v.position2 - q) : 0;
              value = value * 0.6 + other * 0.4;
              v.position2 += v.increment2;
            }
          } else if (v.model) {
            for (let j = 0; j < v.ratios.length; j++)
              if (v.frequency * v.ratios[j] < this.rate * 0.43)
                value += sin(age * v.frequency * v.ratios[j]) * Math.exp(
                  -age * (1 + j * 0.6) / (v.model === "bowl" ? 2.8 : 1.4)
                ) * (j ? 0.3 / (j + 1) : 1);
          } else {
            v.phase += v.frequency / this.rate;
            v.phase -= v.phase | 0;
            v.phase2 += v.frequency * v.detuneRatio / this.rate;
            v.phase2 -= v.phase2 | 0;
            const design = v.design;
            const breathe = sin(age * design.evolution + v.note.color);
            const decay = 1 / (1 + age * design.decay);
            for (let j = 0; j < v.harmonics.length; j++) {
              const band = this.expressionBands[(j + design.trace) % 9];
              let weight = j ? 0.6 + brightness * 0.4 + band * 0.55 : 1;
              if (design.family === "glass") weight *= j ? decay : 0.8;
              else if (design.family === "plume")
                weight *= j ? decay * decay : 0.55 + decay * 0.45;
              else if (design.family === "choir")
                weight *= 0.72 + 0.28 * sin(
                  age * design.evolution + j * 0.22 + this.expression.direction * 0.18
                );
              else if (design.family === "strings")
                weight *= 0.86 + 0.14 * sin(age * design.evolution + j * 0.31);
              else if (design.family === "reed")
                weight *= j % 2 ? 0.7 : 1 + band * 0.25;
              else weight *= j ? 0.84 + 0.16 * breathe : 1;
              const partial = sin(v.phase * (j + 1)) * (1 - design.blend) + sin(v.phase2 * (j + 1)) * design.blend;
              value += partial * v.harmonics[j] * weight;
            }
            value *= (0.9 + energy * 0.14 + breathe * 0.05) * v.attenuation;
          }
          if (v.note.lane === "greeting") {
            const bloom = sin(age * v.frequency) * 0.58 + sin(age * v.frequency * 2) * 0.16;
            let dust = 0;
            for (let k = 0; k < 4; k++) {
              const elapsed = age - k * 0.19, harmonic = k + 2;
              if (elapsed > 0 && v.frequency * harmonic < this.rate * 0.43)
                dust += sin(elapsed * v.frequency * harmonic) * smooth(elapsed / 0.2) * Math.exp(-elapsed / (1.05 + k * 0.16)) * 0.12 / (1 + k * 0.5);
            }
            value = value * 0.3 + bloom * Math.exp(-age / 2.1) + dust;
          }
          value *= envelope * v.gain;
          if (v.note.lane === "synth") {
            const drift = this.expression.direction * 0.13 + sin(age * 0.08 + v.note.pan) * 0.05;
            sl += value * v.panL * (1 - drift);
            sr += value * v.panR * (1 + drift);
          } else if (v.note.lane === "instrument") {
            il += value * v.panL;
            ir += value * v.panR;
          } else {
            gl += value * v.panL;
            gr += value * v.panR;
          }
        }
        const duckTarget = time - this.greetingAt < 1.8 ? 0.48 : 1;
        this.duck += (duckTarget - this.duck) * (duckTarget < this.duck ? duckAttack : duckRelease);
        let left = 0, right = 0;
        for (let j = 0; j < 3; j++) {
          const [bl, br] = this.buses[lanes[j]].process(
            j === 0 ? sl : j === 1 ? il : gl,
            j === 0 ? sr : j === 1 ? ir : gr,
            patches[j]
          );
          const gain = levels[j] * (j < 2 ? this.duck : 1);
          left += bl * gain;
          right += br * gain;
          const peak = Math.max(Math.abs(bl * gain), Math.abs(br * gain));
          if (j === 0) maxS = Math.max(maxS, peak);
          else if (j === 1) maxI = Math.max(maxI, peak);
          else maxG = Math.max(maxG, peak);
        }
        this.dcL += (left - this.dcL) * dc;
        this.dcR += (right - this.dcR) * dc;
        l[i] = Math.tanh((left - this.dcL) * 1.65) * 0.9;
        r[i] = Math.tanh((right - this.dcR) * 1.65) * 0.9;
        if (this.cursor % 128 === 0)
          this.voices = this.voices.filter(
            (v) => time < Math.min(v.stop + v.release, v.forced)
          );
      }
      if (at) this.pending.splice(0, at);
      this.meters = {
        synth: Math.max(maxS, this.meters.synth * 0.92),
        instrument: Math.max(maxI, this.meters.instrument * 0.92),
        greeting: Math.max(maxG, this.meters.greeting * 0.92)
      };
    }
    get time() {
      return this.cursor / this.rate;
    }
    get status() {
      return {
        voices: this.voices.length,
        meters: this.meters,
        greeting: this.time - this.greetingAt < 3.2,
        pending: this.pending.length
      };
    }
  };

  // src/lib/plant-live-engine.ts
  var LIVE_DELAY = 0.12;
  var LiveMusicEngine = class {
    constructor(sampleRate, elapsed = 0, config = defaultConfiguration(), bank = {}) {
      __publicField(this, "composer");
      __publicField(this, "audio");
      __publicField(this, "signal", createSignalAccumulator((frame) => this.frame(frame)));
      __publicField(this, "elapsed");
      __publicField(this, "origin");
      __publicField(this, "lastFrame", -Infinity);
      __publicField(this, "stoppedAt", Infinity);
      __publicField(this, "lastNote", "");
      __publicField(this, "sampleRate");
      __publicField(this, "config");
      __publicField(this, "bank");
      this.sampleRate = sampleRate;
      this.config = config;
      this.bank = bank;
      this.elapsed = this.origin = elapsed;
      this.composer = new Composer(config);
      this.audio = new AudioCore(sampleRate, config, bank);
    }
    schedule(events) {
      this.audio.schedule(
        events.map((e) => {
          const time = Math.max(
            this.audio.time,
            e.time - this.origin + LIVE_DELAY
          );
          if (e.type !== "note") return __spreadProps(__spreadValues({}, e), { time });
          if (e.note.lane === "instrument") this.lastNote = noteName(e.note.midi);
          return __spreadProps(__spreadValues({}, e), {
            time,
            note: __spreadProps(__spreadValues({}, e.note), {
              time,
              sourceTime: e.note.sourceTime - this.origin + LIVE_DELAY
            })
          });
        })
      );
    }
    frame(frame) {
      this.lastFrame = frame.time;
      this.composer.push(frame);
      this.schedule(this.composer.drain());
    }
    push(packet) {
      if (Number.isFinite(this.stoppedAt)) return;
      const time = packet.elapsed_ms / 1e3;
      if (Number.isFinite(time) && time > this.elapsed + 0.75) {
        this.elapsed = this.origin = time;
        this.composer.advance(time);
        this.composer.drain();
        this.audio = new AudioCore(this.sampleRate, this.config, this.bank);
      }
      this.signal.push(packet);
    }
    configure(config, bank = this.bank) {
      this.config = config;
      this.bank = bank;
      this.composer.configure(config, this.elapsed);
      this.audio.configure(config, bank);
      this.schedule(this.composer.drain());
    }
    audition(lane) {
      this.composer.audition(lane, this.elapsed);
      this.schedule(this.composer.drain());
    }
    finish() {
      if (Number.isFinite(this.stoppedAt)) return;
      this.signal.flush();
      this.composer.finish(this.elapsed);
      this.schedule(this.composer.drain());
      this.stoppedAt = this.elapsed;
    }
    render(left, right) {
      this.signal.advance(this.elapsed * 1e3);
      if (!Number.isFinite(this.stoppedAt)) {
        this.composer.advance(this.elapsed);
        this.schedule(this.composer.drain());
      }
      this.audio.render(left, right);
      if (Number.isFinite(this.stoppedAt))
        for (let i = 0; i < left.length; i++) {
          const fade = Math.max(
            0,
            Math.min(
              1,
              RELEASE_SECONDS - (this.elapsed + i / this.sampleRate - this.stoppedAt)
            )
          );
          left[i] *= fade;
          right[i] *= fade;
        }
      this.elapsed += left.length / this.sampleRate;
      return !Number.isFinite(this.stoppedAt) || this.elapsed - this.stoppedAt < RELEASE_SECONDS;
    }
    get status() {
      return __spreadProps(__spreadValues({}, this.audio.status), {
        phase: Number.isFinite(this.stoppedAt) ? "ended" : this.lastFrame === -Infinity ? "waiting" : this.elapsed - this.lastFrame > GAP_SECONDS ? "gap" : "playing",
        synth: preset(this.config.synth.preset).name,
        instrument: preset(this.config.instrument.preset).name,
        note: this.lastNote
      });
    }
    get diagnostics() {
      return __spreadProps(__spreadValues({}, this.audio.status), { invalid: this.signal.invalid });
    }
  };
  return __toCommonJS(plant_live_engine_exports);
})();

  return new Sonora.LiveMusicEngine(rate, elapsed, config, bank);
}
